[app]
port = 4502

[github]
redirect_uri = "https://contribute.qidian.space"
repo_path = "https://github.com/qidiankepukehuan/qidiankepukehuan"

[smtp]
username = "tsblydyzbjb@163.com"
host = "smtp.163.com"

[admin]
emails = [
    "tsblydyzbjb@qidian.space",
    "mudern@qidian.space",
    "shikou@qidian.space"
]

[file]
share_path = "/var"

[log]
level = "info"      # error / warn / info / debug / trace
format = "text"  # text / json / compact
dir = "var/log/qidian"